### ISSUE TITLE
駅に人が集まるときに一点に集中してしまう

### ISSUE THREAD

**Issue by annin3** [traPortation/traPortation-mini#129]
一人が並んでるときと複数人が並んでいるときの違いがわからない

- 並んでいるときに座標を多少バラけるようにして欲しい
- じっとしているのではなく、一定時間で少し駅周辺に座標を変える感じに
- 人が多いときには大きめにバラける感じにして混雑レベルをはっきりわかるようにしたい

**Comment by reyu0722** [comment]
https://github.com/traPortation/traPortation-mini/blob/master/Assets/Scripts/Moving/Section/Person/TrainUsingSection.cs

↑の `TrainUsingSection` 内をいじることになると思います
`Position` は人の位置を表していて、ここを変更するとUI上でも人が動くようになっています
`Status` は人の移動の状態を表していて、`TrainUsingSection` の場合は `NotStarted` `Finished` `OnStation` `OnTrain` のうちいずれかです
(参考: https://github.com/traPortation/traPortation-mini/blob/master/Assets/Scripts/Moving/SectionStatus.cs)

`stations[index]` が今いる駅になっています

`Move(float pos)` はフレームごとに呼ばれます
引数には移動速度が入ります (`pos` になってるのはミスです)

なので、`TrainUsingSection.Status == OnStation` のときに `Move()` 内であれこれすればよさそうです

**Comment by esperanto9657** [comment]
@reyu0722 要求仕様の1番と2番はできましたが、3番の「人が多いときには大きめにバラける感じにして混雑レベルをはっきりわかるようにしたい」に関しましては、「ある駅で待っている人の数」を記録する変数が必要だと思われます。そういった変数はどこかにありますか？もしない場合はどういった設計にする予定ですか？（どのクラスで保持するか、どう更新するか）
